(function(){
  "use strict";
  const STORAGE_KEY="pcb-state-v1",api=window.ChainIndexFolderState,list=document.getElementById("workflowList");
  if(!api||!list)return;
  function readState(){try{const raw=localStorage.getItem(STORAGE_KEY);return api.migrateState(raw?JSON.parse(raw):{})}catch(e){return api.migrateState({})}}
  function writeState(state){state=api.migrateState(state);localStorage.setItem(STORAGE_KEY,JSON.stringify(state));api.persistFolderBackup(state)}
  function esc(v){return String(v==null?"":v).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;").replace(/\"/g,"&quot;").replace(/'/g,"&#39;")}
  function expanded(state,id){state.folderExpanded=state.folderExpanded||{};if(state.folderExpanded[id]==null)state.folderExpanded[id]=true;return state.folderExpanded[id]!==false}
  function workflowHtml(w,active){return '<div class="workflow-item '+(w.id===active?'is-active':'')+'" data-id="'+esc(w.id)+'" draggable="true"><button class="workflow-select" type="button" data-action="select"><span class="workflow-name">'+esc(w.name)+'</span><span class="workflow-meta">'+(w.steps?.length||0)+' Schritte</span></button><div class="workflow-item-actions"><button class="icon-btn-sm" data-action="rename">✎</button><button class="icon-btn-sm" data-action="deeplink">🔗</button><button class="icon-btn-sm" data-action="export">⭳</button><button class="icon-btn-sm icon-btn-danger" data-action="delete">🗑</button></div></div>'}
  function render(){const state=readState(),folders=(state.folders||[]).slice().sort((a,b)=>a.system?-1:b.system?1:a.name.localeCompare(b.name,"de")),workflows=state.workflows||{};list.innerHTML=folders.map(f=>{const open=expanded(state,f.id),items=Object.values(workflows).filter(w=>w&&w.folderId===f.id).sort((a,b)=>(b.updatedAt||0)-(a.updatedAt||0));return '<section class="folder-group" data-folder-id="'+esc(f.id)+'"><div class="folder-header"><button class="folder-toggle" data-folder-action="toggle">'+(open?'▼':'▶')+' 📁 <span class="folder-name">'+esc(f.name)+'</span></button>'+(f.system?'':'<div class="folder-actions"><button class="icon-btn-sm" data-folder-action="rename">✎</button><button class="icon-btn-sm icon-btn-danger" data-folder-action="delete">🗑</button></div>')+'</div><div class="folder-workflows">'+(open?(items.length?items.map(w=>workflowHtml(w,state.activeWorkflowId)).join(""): '<div class="folder-empty">Keine Workflows</div>'):"")+'</div></section>'}).join("")}
  function createFolder(){const name=prompt("Name des neuen Ordners:","");if(name==null)return;try{const state=readState(),folder=api.createFolder(name);state.folders.push(folder);state.activeFolderId=folder.id;state.folderExpanded=state.folderExpanded||{};state.folderExpanded[folder.id]=true;writeState(state);render()}catch(e){alert(e.message)}}
  function renameFolder(group){const state=readState(),id=group.dataset.folderId,f=api.getFolderById(state,id);if(!f||f.system)return;const value=prompt("Ordner umbenennen:",f.name);if(value==null)return;try{api.renameFolder(state,id,value);writeState(state);render()}catch(e){alert(e.message)}}
  function deleteFolder(group){const state=readState(),id=group.dataset.folderId,f=api.getFolderById(state,id);if(!f||f.system)return;if(!confirm('Ordner „'+f.name+'“ löschen?'))return;try{api.deleteFolder(state,id);writeState(state);location.reload()}catch(e){alert(e.message)}}
  const original=document.getElementById("newWorkflowBtn");if(original){const b=document.createElement("button");b.id="newFolderBtn";b.className="btn-new-workflow";b.textContent="+ Neuer Ordner";original.insertAdjacentElement("afterend",b);b.onclick=createFolder}
  list.addEventListener("click",e=>{const group=e.target.closest(".folder-group");if(!group)return;const a=e.target.closest("[data-folder-action]");if(!a)return;e.preventDefault();e.stopPropagation();const state=readState(),id=group.dataset.folderId;if(a.dataset.folderAction==="toggle"){state.folderExpanded=state.folderExpanded||{};state.folderExpanded[id]=!expanded(state,id);writeState(state);render()}else if(a.dataset.folderAction==="rename")renameFolder(group);else if(a.dataset.folderAction==="delete")deleteFolder(group)},true);
  render();
})();
