(function(){
  "use strict";
  const SYSTEM_FOLDER_NAME="Unsortiert",SYSTEM_FOLDER_ID="folder-unsorted",FOLDER_BACKUP_KEY="pcb-workflow-folders-v1",STORAGE_KEY="pcb-state-v1";
  function uid(){return window.crypto&&crypto.randomUUID?crypto.randomUUID():"id-"+Date.now().toString(36)+"-"+Math.random().toString(36).slice(2,9)}
  function now(){return new Date().toISOString()}
  function createSystemFolder(){const timestamp=now();return{id:SYSTEM_FOLDER_ID,name:SYSTEM_FOLDER_NAME,createdAt:timestamp,updatedAt:timestamp,system:true}}
  function createFolder(name){const value=String(name==null?"":name).trim();if(!value)throw new Error("Der Ordnername darf nicht leer sein.");if(value===SYSTEM_FOLDER_NAME)throw new Error("Der Systemordner darf nicht erneut angelegt werden.");const timestamp=now();return{id:"folder-"+uid(),name:value,createdAt:timestamp,updatedAt:timestamp,system:false}}
  function getFolderById(state,folderId){return state&&Array.isArray(state.folders)?state.folders.find(folder=>folder.id===folderId)||null:null}
  function ensureSystemFolder(state){if(!state||typeof state!=="object")throw new Error("Ungültiger State.");if(!Array.isArray(state.folders))state.folders=[];let systemFolder=state.folders.find(folder=>folder.system===true||folder.id===SYSTEM_FOLDER_ID);if(!systemFolder){systemFolder=createSystemFolder();state.folders.unshift(systemFolder)}else{systemFolder.id=SYSTEM_FOLDER_ID;systemFolder.name=SYSTEM_FOLDER_NAME;systemFolder.system=true;systemFolder.createdAt=systemFolder.createdAt||now();systemFolder.updatedAt=systemFolder.updatedAt||systemFolder.createdAt}return systemFolder}
  function readBackup(){try{const raw=localStorage.getItem(FOLDER_BACKUP_KEY);return raw?JSON.parse(raw):null}catch(e){return null}}
  function restoreFolderBackup(state){const backup=readBackup();if(!backup||!Array.isArray(backup.folders)||!backup.folders.length)return state;const br=Number(backup.revision||0),sr=Number(state.folderStateRevision||0);if(br>sr||!Array.isArray(state.folders)||state.folders.length<=1){state.folders=backup.folders.map(f=>Object.assign({},f));state.folderExpanded=Object.assign({},backup.folderExpanded||{},state.folderExpanded||{});if(backup.activeFolderId)state.activeFolderId=backup.activeFolderId;state.folderStateRevision=br}return state}
  function normalizeWorkflows(state){if(!state||typeof state!=="object")throw new Error("Ungültiger State.");if(!state.workflows)state.workflows={};restoreFolderBackup(state);const systemFolder=ensureSystemFolder(state);Object.keys(state.workflows).forEach(id=>{const workflow=state.workflows[id];if(!workflow||typeof workflow!=="object")return;workflow.id=workflow.id||id;workflow.folderId=getFolderById(state,workflow.folderId)?workflow.folderId:systemFolder.id});if(!state.activeFolderId||!getFolderById(state,state.activeFolderId)){const active=state.workflows[state.activeWorkflowId];state.activeFolderId=active&&getFolderById(state,active.folderId)?active.folderId:systemFolder.id}if(!state.folderExpanded||typeof state.folderExpanded!=="object")state.folderExpanded={};if(state.folderExpanded[systemFolder.id]==null)state.folderExpanded[systemFolder.id]=true;return state}
  function migrateState(input){return normalizeWorkflows(input&&typeof input==="object"?input:{})}
  function renameFolder(state,folderId,name){const folder=getFolderById(state,folderId);if(!folder)throw new Error("Ordner nicht gefunden.");if(folder.system)throw new Error("Der Systemordner darf nicht umbenannt werden.");const value=String(name==null?"":name).trim();if(!value)throw new Error("Der Ordnername darf nicht leer sein.");if(state.folders.some(item=>item.id!==folder.id&&item.name.toLowerCase()===value.toLowerCase()))throw new Error("Ein Ordner mit diesem Namen existiert bereits.");folder.name=value;folder.updatedAt=now();persistFolderBackup(state);return folder}
  function deleteFolder(state,folderId){const folder=getFolderById(state,folderId);if(!folder)throw new Error("Ordner nicht gefunden.");if(folder.system)throw new Error("Der Systemordner darf nicht gelöscht werden.");const systemFolder=ensureSystemFolder(state);Object.values(state.workflows||{}).forEach(workflow=>{if(workflow&&workflow.folderId===folderId)workflow.folderId=systemFolder.id});state.folders=state.folders.filter(item=>item.id!==folderId);if(state.folderExpanded)delete state.folderExpanded[folderId];if(state.activeFolderId===folderId)state.activeFolderId=systemFolder.id;persistFolderBackup(state);return systemFolder.id}
  function moveWorkflowToFolder(state,workflowId,folderId){const workflow=state.workflows&&state.workflows[workflowId];if(!workflow)throw new Error("Workflow nicht gefunden.");if(!getFolderById(state,folderId))throw new Error("Ungültige folderId.");workflow.folderId=folderId;workflow.updatedAt=now();state.activeFolderId=folderId;persistFolderBackup(state);return workflow}
  function getWorkflowsForFolder(state,folderId){return getFolderById(state,folderId)?Object.values(state.workflows||{}).filter(workflow=>workflow&&workflow.folderId===folderId):[]}
  function persistFolderBackup(state){try{const revision=Date.now();state.folderStateRevision=revision;localStorage.setItem(FOLDER_BACKUP_KEY,JSON.stringify({revision,folders:state.folders||[],folderExpanded:state.folderExpanded||{},activeFolderId:state.activeFolderId||SYSTEM_FOLDER_ID,version:3}))}catch(e){console.warn("Folder-Backup konnte nicht gespeichert werden.",e)}}
  function protectWorkflowStorage(){if(window.__chainindexFolderStorageGuard)return;const original=localStorage.setItem.bind(localStorage);localStorage.setItem=function(key,value){if(key===STORAGE_KEY){try{const incoming=JSON.parse(value);const backup=readBackup();if(backup&&Array.isArray(backup.folders)){const incomingRevision=Number(incoming.folderStateRevision||0),backupRevision=Number(backup.revision||0);if(backupRevision>incomingRevision||!Array.isArray(incoming.folders)||incoming.folders.length<=1){incoming.folders=backup.folders.map(f=>Object.assign({},f));incoming.folderExpanded=Object.assign({},backup.folderExpanded||{},incoming.folderExpanded||{});incoming.activeFolderId=backup.activeFolderId||incoming.activeFolderId||SYSTEM_FOLDER_ID;incoming.folderStateRevision=backupRevision;value=JSON.stringify(incoming)}}}catch(e){console.warn("Folder-State konnte beim Speichern nicht geschützt werden.",e)}}return original(key,value)};window.__chainindexFolderStorageGuard=true}
  protectWorkflowStorage();
  window.ChainIndexFolderState={SYSTEM_FOLDER_ID,SYSTEM_FOLDER_NAME,FOLDER_BACKUP_KEY,createSystemFolder,createFolder,renameFolder,deleteFolder,moveWorkflowToFolder,getFolderById,getWorkflowsForFolder,migrateState,ensureSystemFolder,persistFolderBackup};
  const scripts=["node-model.js","folder-ui.js","prompt-nav.js","folder-dragdrop.js"];scripts.forEach(src=>{const s=document.createElement("script");s.src="./"+src;s.async=false;document.body.appendChild(s)});
})();